# Generated by Django 5.0.14 on 2025-12-09 19:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaInfo',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('bounds_lat_min', models.FloatField()),
                ('bounds_lat_max', models.FloatField()),
                ('bounds_lng_min', models.FloatField()),
                ('bounds_lng_max', models.FloatField()),
            ],
            options={
                'verbose_name': 'Area Information',
                'verbose_name_plural': 'Area Information',
                'db_table': 'area_info',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='EmissionData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('transport', models.FloatField(default=0)),
                ('industry', models.FloatField(default=0)),
                ('energy', models.FloatField(default=0)),
                ('waste', models.FloatField(default=0)),
                ('buildings', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('data_type', models.CharField(choices=[('historical', 'Historical'), ('forecast', 'Forecast')], default='historical', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emissions', to='api.areainfo')),
            ],
            options={
                'db_table': 'emission_data',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['area', 'date'], name='emission_da_area_id_b5b9cd_idx'), models.Index(fields=['date'], name='emission_da_date_f8f319_idx'), models.Index(fields=['data_type'], name='emission_da_data_ty_e114a8_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('emissions', models.FloatField()),
                ('trend', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('stable', 'Stable')], max_length=10)),
                ('trend_percentage', models.FloatField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.areainfo')),
            ],
            options={
                'db_table': 'leaderboard_entries',
                'ordering': ['rank'],
                'indexes': [models.Index(fields=['period_start', 'period_end'], name='leaderboard_period__97ebdc_idx')],
            },
        ),
    ]
