# Generated by Django 5.0.14 on 2025-12-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supabase_id',
            field=models.CharField(blank=True, help_text='Supabase auth user ID for linking accounts', max_length=255, null=True, unique=True),
        ),
    ]
