"""
CarbonSense Policy Registry
============================

A comprehensive registry of 100+ climate policy documents (2020-2026) relevant
to carbon emission reduction in Lahore, Pakistan. Documents are organized into
four tiers:

    Tier 1 - Pakistan-specific policies, plans, and regulations
    Tier 2 - South Asian regional policies and frameworks
    Tier 3 - International frameworks, agreements, and technical reports
    Tier 4 - Case studies from comparable cities and countries

Each entry covers one or more of five sectors:
    transport, industry, energy, waste, buildings

URLs are provided where stable public links are known (especially for
international organizations like IPCC, UNFCCC, IEA, IRENA, World Bank).
For Pakistan government documents whose URLs may be unstable or require
manual retrieval, `url` is set to None and `manual_note` provides guidance.
"""

POLICY_REGISTRY = [
    # =========================================================================
    # TIER 1 — Pakistan-Specific (~50 entries)
    # =========================================================================

    # --- National Climate & NDC ---
    {
        "id": "pakistan_updated_ndc_2021",
        "title": "Pakistan Updated Nationally Determined Contributions 2021",
        "url": "https://unfccc.int/sites/default/files/NDC/2022-06/Pakistan%20Updated%20NDC%202021.pdf",
        "country": "Pakistan",
        "region": "",
        "city": "",
        "sectors": ["transport", "industry", "energy", "waste", "buildings"],
        "year": 2021,
        "policy_type": "framework",
        "scale": "national",
        "effectiveness_rating": "proven",
        "source_organization": "Ministry of Climate Change, Government of Pakistan",
        "tier": 1,
        "manual_note": None,
    },
    {
        "id": "pakistan_national_adaptation_plan_2023",
        "title": "Pakistan National Adaptation Plan 2023",
        "url": None,
        "country": "Pakistan",
        "region": "",
        "city": "",
        "sectors": ["transport", "industry", "energy", "waste", "buildings"],
        "year": 2023,
        "policy_type": "framework",
        "scale": "national",
        "effectiveness_rating": "promising",
        "source_organization": "Ministry of Climate Change, Government of Pakistan",
        "tier": 1,
        "manual_note": "Available from the Ministry of Climate Change website or UNFCCC NAP Central repository.",
    },
    {
        "id": "pakistan_national_climate_change_policy_2021",
        "title": "Pakistan National Climate Change Policy (Amended 2021)",
        "url": None,
        "country": "Pakistan",
        "region": "",
        "city": "",
        "sectors": ["transport", "industry", "energy", "waste", "buildings"],
        "year": 2021,
        "policy_type": "legislation",
        "scale": "national",
        "effectiveness_rating": "proven",
        "source_organization": "Ministry of Climate Change, Government of Pakistan",
        "tier": 1,
        "manual_note": "Request from Ministry of Climate Change or Pakistan Climate Change Authority.",
    },
    {
        "id": "pakistan_climate_change_act_2017_amendment_2022",
        "title": "Pakistan Climate Change Act 2017 (Amendment 2022)",
        "url": None,
        "country": "Pakistan",
        "region": "",
        "city": "",
        "sectors": ["transport", "industry", "energy", "waste", "buildings"],
        "year": 2022,
        "policy_type": "legislation",
        "scale": "national",
        "effectiveness_rating": "proven",
        "source_organization": "National Assembly of Pakistan",
        "tier": 1,
        "manual_note": "Available from Pakistan Gazette or National Assembly legislative records.",
    },
    {
        "id": "pakistan_climate_change_authority_annual_report_2023",
        "title": "Pakistan Climate Change Authority Annual Report 2023",
        "url": None,
        "country": "Pakistan",
        "region": "",
        "city": "",
        "sectors": ["transport", "industry", "energy", "waste", "buildings"],
        "year": 2023,
        "policy_type": "technical_report",
        "scale": "national",
        "effectiveness_rating": "",
        "source_organization": "Pakistan Climate Change Authority",
        "tier": 1,
        "manual_note": "Request from Pakistan Climate Change Authority (PCCA) offices.",
    },
    {
        "id": "pakistan_national_climate_finance_strategy_2022",
        "title": "Pakistan National Climate Finance Strategy 2022",
        "url": None,
        "country": "Pakistan",
        "region": "",
        "city": "",
        "sectors": ["transport", "industry", "energy", "waste", "buildings"],
        "year": 2022,
        "policy_type": "framework",
        "scale": "national",
        "effectiveness_rating": "promising",
        "source_organization": "Ministry of Finance & Ministry of Climate Change, Government of Pakistan",
        "tier": 1,
        "manual_note": "Available through UNDP Pakistan or Ministry of Finance.",
    },
    {
        "id": "pakistan_loss_and_damage_position_paper_2022",
        "title": "Pakistan Position Paper on Loss and Damage (COP27)",
        "url": None,
        "country": "Pakistan",
        "region": "",
        "city": "",
        "sectors": ["transport", "industry", "energy", "waste", "buildings"],
        "year": 2022,
        "policy_type": "framework",
        "scale": "national",
        "effectiveness_rating": "theoretical",
        "source_organization": "Ministry of Climate Change, Government of Pakistan",
        "tier": 1,
        "manual_note": "Available from UNFCCC submissions portal or Ministry of Climate Change.",
    },
    {
        "id": "pakistan_resilient_recovery_rehabilitation_reconstruction_framework_2022",
        "title": "Pakistan Resilient Recovery, Rehabilitation and Reconstruction Framework (4RF) 2022",
        "url": None,
        "country": "Pakistan",
        "region": "",
        "city": "",
        "sectors": ["transport", "industry", "energy", "buildings"],
        "year": 2022,
        "policy_type": "framework",
        "scale": "national",
        "effectiveness_rating": "promising",
        "source_organization": "Government of Pakistan / World Bank / UNDP",
        "tier": 1,
        "manual_note": "Available from Planning Commission or World Bank Pakistan page.",
    },
    {
        "id": "pakistan_living_indus_initiative_2022",
        "title": "Living Indus Initiative 2022",
        "url": None,
        "country": "Pakistan",
        "region": "",
        "city": "",
        "sectors": ["energy", "waste"],
        "year": 2022,
        "policy_type": "framework",
        "scale": "national",
        "effectiveness_rating": "promising",
        "source_organization": "Ministry of Climate Change / UNDP Pakistan",
        "tier": 1,
        "manual_note": "Available from UNDP Pakistan or Ministry of Climate Change.",
    },

    # --- Energy ---
    {
        "id": "pakistan_alternative_renewable_energy_policy_2020",
        "title": "Pakistan Alternative and Renewable Energy Policy 2020",
        "url": None,
        "country": "Pakistan",
        "region": "",
        "city": "",
        "sectors": ["energy"],
        "year": 2020,
        "policy_type": "legislation",
        "scale": "national",
        "effectiveness_rating": "proven",
        "source_organization": "Ministry of Energy (Power Division), Government of Pakistan",
        "tier": 1,
        "manual_note": "Available from AEDB website or Ministry of Energy (Power Division).",
    },
    {
        "id": "pakistan_solar_energy_policy_2020",
        "title": "Pakistan Solar Energy Policy 2020",
        "url": None,
        "country": "Pakistan",
        "region": "",
        "city": "",
        "sectors": ["energy"],
        "year": 2020,
        "policy_type": "legislation",
        "scale": "national",
        "effectiveness_rating": "promising",
        "source_organization": "Alternative Energy Development Board (AEDB)",
        "tier": 1,
        "manual_note": "Available from AEDB website (www.aedb.org).",
    },
    {
        "id": "pakistan_aedb_progress_report_2023",
        "title": "AEDB Annual Progress Report on Renewable Energy 2023",
        "url": None,
        "country": "Pakistan",
        "region": "",
        "city": "",
        "sectors": ["energy"],
        "year": 2023,
        "policy_type": "technical_report",
        "scale": "national",
        "effectiveness_rating": "",
        "source_organization": "Alternative Energy Development Board (AEDB)",
        "tier": 1,
        "manual_note": "Request from AEDB or Ministry of Energy.",
    },
    {
        "id": "pakistan_integrated_energy_plan_2023",
        "title": "Pakistan Integrated Energy Plan 2023-2030",
        "url": None,
        "country": "Pakistan",
        "region": "",
        "city": "",
        "sectors": ["energy", "industry"],
        "year": 2023,
        "policy_type": "framework",
        "scale": "national",
        "effectiveness_rating": "promising",
        "source_organization": "Ministry of Energy / Planning Commission, Government of Pakistan",
        "tier": 1,
        "manual_note": "Available from Ministry of Energy or Planning Commission.",
    },
    {
        "id": "neeca_energy_conservation_guidelines_2021",
        "title": "NEECA National Energy Efficiency and Conservation Guidelines 2021",
        "url": None,
        "country": "Pakistan",
        "region": "",
        "city": "",
        "sectors": ["energy", "buildings", "industry"],
        "year": 2021,
        "policy_type": "guideline",
        "scale": "national",
        "effectiveness_rating": "promising",
        "source_organization": "National Energy Efficiency and Conservation Authority (NEECA)",
        "tier": 1,
        "manual_note": "Available from NEECA website (www.neeca.gov.pk).",
    },
    {
        "id": "neeca_industrial_energy_audit_framework_2022",
        "title": "NEECA Framework for Industrial Energy Audits 2022",
        "url": None,
        "country": "Pakistan",
        "region": "",
        "city": "",
        "sectors": ["industry", "energy"],
        "year": 2022,
        "policy_type": "guideline",
        "scale": "national",
        "effectiveness_rating": "promising",
        "source_organization": "National Energy Efficiency and Conservation Authority (NEECA)",
        "tier": 1,
        "manual_note": "Available from NEECA (www.neeca.gov.pk).",
    },
    {
        "id": "neeca_building_energy_labeling_2023",
        "title": "NEECA Building Energy Performance Labeling Guidelines 2023",
        "url": None,
        "country": "Pakistan",
        "region": "",
        "city": "",
        "sectors": ["buildings", "energy"],
        "year": 2023,
        "policy_type": "guideline",
        "scale": "national",
        "effectiveness_rating": "theoretical",
        "source_organization": "National Energy Efficiency and Conservation Authority (NEECA)",
        "tier": 1,
        "manual_note": "Available from NEECA (www.neeca.gov.pk).",
    },

    # --- Transport ---
    {
        "id": "pakistan_national_ev_policy_2020",
        "title": "Pakistan National Electric Vehicles Policy 2020",
        "url": None,
        "country": "Pakistan",
        "region": "",
        "city": "",
        "sectors": ["transport"],
        "year": 2020,
        "policy_type": "legislation",
        "scale": "national",
        "effectiveness_rating": "promising",
        "source_organization": "Ministry of Industries & Production / Ministry of Climate Change",
        "tier": 1,
        "manual_note": "Available from Ministry of Industries & Production or Engineering Development Board.",
    },
    {
        "id": "pakistan_national_transport_policy_2020",
        "title": "Pakistan National Transport Policy 2020",
        "url": None,
        "country": "Pakistan",
        "region": "",
        "city": "",
        "sectors": ["transport"],
        "year": 2020,
        "policy_type": "legislation",
        "scale": "national",
        "effectiveness_rating": "promising",
        "source_organization": "Ministry of Communications, Government of Pakistan",
        "tier": 1,
        "manual_note": "Available from Ministry of Communications.",
    },
    {
        "id": "pakistan_national_freight_transport_strategy_2021",
        "title": "Pakistan National Freight and Logistics Policy Framework 2021",
        "url": None,
        "country": "Pakistan",
        "region": "",
        "city": "",
        "sectors": ["transport"],
        "year": 2021,
        "policy_type": "framework",
        "scale": "national",
        "effectiveness_rating": "theoretical",
        "source_organization": "Ministry of Communications, Government of Pakistan",
        "tier": 1,
        "manual_note": "Available from Ministry of Communications or Planning Commission.",
    },
    {
        "id": "lahore_brt_orange_line_emissions_assessment_2021",
        "title": "Lahore Orange Line Metro: Emissions Reduction Assessment 2021",
        "url": None,
        "country": "Pakistan",
        "region": "Punjab",
        "city": "Lahore",
        "sectors": ["transport"],
        "year": 2021,
        "policy_type": "technical_report",
        "scale": "local",
        "effectiveness_rating": "proven",
        "source_organization": "Punjab Mass Transit Authority / Lahore Transport Company",
        "tier": 1,
        "manual_note": "Available from Punjab Mass Transit Authority or Lahore Transport Company.",
    },
    {
        "id": "lahore_transport_master_plan_2022",
        "title": "Lahore Urban Transport Master Plan 2022",
        "url": None,
        "country": "Pakistan",
        "region": "Punjab",
        "city": "Lahore",
        "sectors": ["transport"],
        "year": 2022,
        "policy_type": "framework",
        "scale": "local",
        "effectiveness_rating": "promising",
        "source_organization": "Lahore Development Authority / JICA",
        "tier": 1,
        "manual_note": "Request from Lahore Development Authority (LDA) or JICA Pakistan office.",
    },

    # --- Buildings ---
    {
        "id": "pakistan_building_energy_code_2023",
        "title": "Pakistan Building Energy Code 2023",
        "url": None,
        "country": "Pakistan",
        "region": "",
        "city": "",
        "sectors": ["buildings", "energy"],
        "year": 2023,
        "policy_type": "legislation",
        "scale": "national",
        "effectiveness_rating": "promising",
        "source_organization": "NEECA / Ministry of Housing and Works",
        "tier": 1,
        "manual_note": "Available from NEECA or Pakistan Engineering Council (PEC).",
    },
    {
        "id": "pakistan_green_building_guidelines_2022",
        "title": "Pakistan Green Building Guidelines 2022",
        "url": None,
        "country": "Pakistan",
        "region": "",
        "city": "",
        "sectors": ["buildings"],
        "year": 2022,
        "policy_type": "guideline",
        "scale": "national",
        "effectiveness_rating": "theoretical",
        "source_organization": "Pakistan Green Building Council / NEECA",
        "tier": 1,
        "manual_note": "Available from Pakistan Green Building Council.",
    },

    # --- Industry ---
    {
        "id": "pakistan_industrial_policy_2020",
        "title": "Pakistan Industrial Policy 2020",
        "url": None,
        "country": "Pakistan",
        "region": "",
        "city": "",
        "sectors": ["industry"],
        "year": 2020,
        "policy_type": "legislation",
        "scale": "national",
        "effectiveness_rating": "promising",
        "source_organization": "Ministry of Industries & Production, Government of Pakistan",
        "tier": 1,
        "manual_note": "Available from Ministry of Industries & Production.",
    },
    {
        "id": "pakistan_sme_green_financing_guidelines_2022",
        "title": "Pakistan SME Green Financing Guidelines 2022",
        "url": None,
        "country": "Pakistan",
        "region": "",
        "city": "",
        "sectors": ["industry"],
        "year": 2022,
        "policy_type": "guideline",
        "scale": "national",
        "effectiveness_rating": "theoretical",
        "source_organization": "State Bank of Pakistan / SMEDA",
        "tier": 1,
        "manual_note": "Available from State Bank of Pakistan or SMEDA.",
    },
    {
        "id": "pakistan_brick_kiln_conversion_policy_2021",
        "title": "Pakistan Brick Kiln Zigzag Conversion Policy 2021",
        "url": None,
        "country": "Pakistan",
        "region": "",
        "city": "",
        "sectors": ["industry"],
        "year": 2021,
        "policy_type": "legislation",
        "scale": "national",
        "effectiveness_rating": "proven",
        "source_organization": "Ministry of Climate Change / Punjab EPA",
        "tier": 1,
        "manual_note": "Available from Punjab EPA or Ministry of Climate Change.",
    },
    {
        "id": "lahore_industrial_emissions_inventory_2023",
        "title": "Lahore Industrial Area Emissions Inventory 2023",
        "url": None,
        "country": "Pakistan",
        "region": "Punjab",
        "city": "Lahore",
        "sectors": ["industry"],
        "year": 2023,
        "policy_type": "technical_report",
        "scale": "local",
        "effectiveness_rating": "",
        "source_organization": "Punjab EPA / Lahore Chamber of Commerce and Industry",
        "tier": 1,
        "manual_note": "Request from Punjab Environmental Protection Agency.",
    },

    # --- Waste ---
    {
        "id": "pakistan_solid_waste_management_rules_2021",
        "title": "Pakistan Solid Waste Management Rules 2021",
        "url": None,
        "country": "Pakistan",
        "region": "",
        "city": "",
        "sectors": ["waste"],
        "year": 2021,
        "policy_type": "legislation",
        "scale": "national",
        "effectiveness_rating": "promising",
        "source_organization": "Ministry of Climate Change, Government of Pakistan",
        "tier": 1,
        "manual_note": "Available from Pakistan Gazette or Ministry of Climate Change.",
    },
    {
        "id": "pakistan_hazardous_waste_management_rules_2021",
        "title": "Pakistan Hazardous Waste Management Rules 2021",
        "url": None,
        "country": "Pakistan",
        "region": "",
        "city": "",
        "sectors": ["waste", "industry"],
        "year": 2021,
        "policy_type": "legislation",
        "scale": "national",
        "effectiveness_rating": "promising",
        "source_organization": "Ministry of Climate Change, Government of Pakistan",
        "tier": 1,
        "manual_note": "Available from Pakistan Gazette.",
    },
    {
        "id": "lahore_waste_management_company_strategic_plan_2022",
        "title": "Lahore Waste Management Company Strategic Plan 2022-2027",
        "url": None,
        "country": "Pakistan",
        "region": "Punjab",
        "city": "Lahore",
        "sectors": ["waste"],
        "year": 2022,
        "policy_type": "framework",
        "scale": "local",
        "effectiveness_rating": "promising",
        "source_organization": "Lahore Waste Management Company (LWMC)",
        "tier": 1,
        "manual_note": "Available from LWMC (www.lwmc.com.pk).",
    },
    {
        "id": "lahore_composting_waste_to_energy_feasibility_2023",
        "title": "Lahore Composting and Waste-to-Energy Feasibility Study 2023",
        "url": None,
        "country": "Pakistan",
        "region": "Punjab",
        "city": "Lahore",
        "sectors": ["waste", "energy"],
        "year": 2023,
        "policy_type": "technical_report",
        "scale": "local",
        "effectiveness_rating": "theoretical",
        "source_organization": "LWMC / GIZ Pakistan",
        "tier": 1,
        "manual_note": "Request from Lahore Waste Management Company or GIZ Pakistan.",
    },

    # --- Punjab / Lahore Air Quality & Smog ---
    {
        "id": "punjab_clean_air_action_plan_2023",
        "title": "Punjab Clean Air Action Plan 2023",
        "url": None,
        "country": "Pakistan",
        "region": "Punjab",
        "city": "",
        "sectors": ["transport", "industry", "energy"],
        "year": 2023,
        "policy_type": "framework",
        "scale": "national",
        "effectiveness_rating": "promising",
        "source_organization": "Punjab Environmental Protection Agency",
        "tier": 1,
        "manual_note": "Available from Punjab EPA (www.epd.punjab.gov.pk).",
    },
    {
        "id": "lahore_smog_commission_recommendations_2022",
        "title": "Lahore Smog Commission Recommendations 2022",
        "url": None,
        "country": "Pakistan",
        "region": "Punjab",
        "city": "Lahore",
        "sectors": ["transport", "industry", "energy", "waste"],
        "year": 2022,
        "policy_type": "guideline",
        "scale": "local",
        "effectiveness_rating": "promising",
        "source_organization": "Lahore High Court Smog Commission",
        "tier": 1,
        "manual_note": "Available from Lahore High Court records or Punjab EPA.",
    },
    {
        "id": "lahore_smog_commission_report_2023",
        "title": "Lahore Smog Commission Report and Directives 2023",
        "url": None,
        "country": "Pakistan",
        "region": "Punjab",
        "city": "Lahore",
        "sectors": ["transport", "industry", "energy", "waste"],
        "year": 2023,
        "policy_type": "guideline",
        "scale": "local",
        "effectiveness_rating": "proven",
        "source_organization": "Lahore High Court Smog Commission",
        "tier": 1,
        "manual_note": "Available from Lahore High Court records or Punjab EPA.",
    },
    {
        "id": "punjab_epa_brick_kiln_orders_2022",
        "title": "Punjab EPA Orders on Brick Kiln Emissions Control 2022",
        "url": None,
        "country": "Pakistan",
        "region": "Punjab",
        "city": "",
        "sectors": ["industry"],
        "year": 2022,
        "policy_type": "legislation",
        "scale": "national",
        "effectiveness_rating": "proven",
        "source_organization": "Punjab Environmental Protection Agency",
        "tier": 1,
        "manual_note": "Available from Punjab EPA.",
    },
    {
        "id": "punjab_epa_vehicular_emissions_standards_2021",
        "title": "Punjab EPA Vehicular Emission Standards Notification 2021",
        "url": None,
        "country": "Pakistan",
        "region": "Punjab",
        "city": "",
        "sectors": ["transport"],
        "year": 2021,
        "policy_type": "legislation",
        "scale": "national",
        "effectiveness_rating": "promising",
        "source_organization": "Punjab Environmental Protection Agency",
        "tier": 1,
        "manual_note": "Available from Punjab EPA gazette notifications.",
    },
    {
        "id": "punjab_epa_industrial_emissions_standards_2021",
        "title": "Punjab EPA Industrial Air Emission Standards 2021",
        "url": None,
        "country": "Pakistan",
        "region": "Punjab",
        "city": "",
        "sectors": ["industry"],
        "year": 2021,
        "policy_type": "legislation",
        "scale": "national",
        "effectiveness_rating": "promising",
        "source_organization": "Punjab Environmental Protection Agency",
        "tier": 1,
        "manual_note": "Available from Punjab EPA gazette notifications.",
    },
    {
        "id": "lahore_air_quality_monitoring_report_2023",
        "title": "Lahore Air Quality Monitoring and Analysis Report 2023",
        "url": None,
        "country": "Pakistan",
        "region": "Punjab",
        "city": "Lahore",
        "sectors": ["transport", "industry", "energy"],
        "year": 2023,
        "policy_type": "technical_report",
        "scale": "local",
        "effectiveness_rating": "",
        "source_organization": "Punjab EPA / US Consulate Lahore AQI Station",
        "tier": 1,
        "manual_note": "Request from Punjab EPA or see AirNow.gov for US Consulate data.",
    },

    # --- Additional Pakistan documents ---
    {
        "id": "pakistan_ten_billion_tree_tsunami_update_2023",
        "title": "Pakistan Ten Billion Tree Tsunami Programme Progress Report 2023",
        "url": None,
        "country": "Pakistan",
        "region": "",
        "city": "",
        "sectors": ["energy", "waste"],
        "year": 2023,
        "policy_type": "technical_report",
        "scale": "national",
        "effectiveness_rating": "promising",
        "source_organization": "Ministry of Climate Change, Government of Pakistan",
        "tier": 1,
        "manual_note": "Available from Ministry of Climate Change.",
    },
    {
        "id": "pakistan_green_banking_guidelines_sbp_2022",
        "title": "State Bank of Pakistan Green Banking Guidelines 2022",
        "url": None,
        "country": "Pakistan",
        "region": "",
        "city": "",
        "sectors": ["industry", "energy", "buildings"],
        "year": 2022,
        "policy_type": "guideline",
        "scale": "national",
        "effectiveness_rating": "promising",
        "source_organization": "State Bank of Pakistan",
        "tier": 1,
        "manual_note": "Available from SBP website (www.sbp.org.pk).",
    },
    {
        "id": "pakistan_nepra_net_metering_regulations_2023",
        "title": "NEPRA Net Metering Regulations (Amended 2023)",
        "url": None,
        "country": "Pakistan",
        "region": "",
        "city": "",
        "sectors": ["energy", "buildings"],
        "year": 2023,
        "policy_type": "legislation",
        "scale": "national",
        "effectiveness_rating": "proven",
        "source_organization": "National Electric Power Regulatory Authority (NEPRA)",
        "tier": 1,
        "manual_note": "Available from NEPRA website (www.nepra.org.pk).",
    },
    {
        "id": "pakistan_carbon_market_readiness_assessment_2023",
        "title": "Pakistan Carbon Market Readiness Assessment 2023",
        "url": None,
        "country": "Pakistan",
        "region": "",
        "city": "",
        "sectors": ["industry", "energy"],
        "year": 2023,
        "policy_type": "technical_report",
        "scale": "national",
        "effectiveness_rating": "theoretical",
        "source_organization": "World Bank / Ministry of Climate Change",
        "tier": 1,
        "manual_note": "Available from World Bank Pakistan or PMR (Partnership for Market Readiness).",
    },
    {
        "id": "lahore_development_authority_green_building_bylaws_2023",
        "title": "Lahore Development Authority Green Building Bylaws 2023",
        "url": None,
        "country": "Pakistan",
        "region": "Punjab",
        "city": "Lahore",
        "sectors": ["buildings"],
        "year": 2023,
        "policy_type": "legislation",
        "scale": "local",
        "effectiveness_rating": "theoretical",
        "source_organization": "Lahore Development Authority (LDA)",
        "tier": 1,
        "manual_note": "Request from Lahore Development Authority.",
    },
    {
        "id": "pakistan_auto_industry_development_policy_2021",
        "title": "Pakistan Automotive Industry Development and Export Policy 2021-2026",
        "url": None,
        "country": "Pakistan",
        "region": "",
        "city": "",
        "sectors": ["transport", "industry"],
        "year": 2021,
        "policy_type": "legislation",
        "scale": "national",
        "effectiveness_rating": "promising",
        "source_organization": "Ministry of Industries & Production / Engineering Development Board",
        "tier": 1,
        "manual_note": "Available from Engineering Development Board (EDB) website.",
    },
    {
        "id": "pakistan_petroleum_policy_2020",
        "title": "Pakistan Petroleum Policy 2020",
        "url": None,
        "country": "Pakistan",
        "region": "",
        "city": "",
        "sectors": ["energy", "industry"],
        "year": 2020,
        "policy_type": "legislation",
        "scale": "national",
        "effectiveness_rating": "promising",
        "source_organization": "Ministry of Energy (Petroleum Division), Government of Pakistan",
        "tier": 1,
        "manual_note": "Available from Ministry of Energy (Petroleum Division).",
    },
    {
        "id": "pakistan_ogra_cng_policy_revision_2022",
        "title": "OGRA CNG Sector Policy Revision 2022",
        "url": None,
        "country": "Pakistan",
        "region": "",
        "city": "",
        "sectors": ["transport", "energy"],
        "year": 2022,
        "policy_type": "legislation",
        "scale": "national",
        "effectiveness_rating": "promising",
        "source_organization": "Oil and Gas Regulatory Authority (OGRA)",
        "tier": 1,
        "manual_note": "Available from OGRA website.",
    },
    {
        "id": "pakistan_flood_post_disaster_needs_assessment_2022",
        "title": "Pakistan 2022 Floods: Post-Disaster Needs Assessment",
        "url": "https://www.undp.org/pakistan/publications/pakistan-floods-2022-post-disaster-needs-assessment",
        "country": "Pakistan",
        "region": "",
        "city": "",
        "sectors": ["transport", "industry", "energy", "waste", "buildings"],
        "year": 2022,
        "policy_type": "technical_report",
        "scale": "national",
        "effectiveness_rating": "",
        "source_organization": "Government of Pakistan / Asian Development Bank / EU / UNDP / World Bank",
        "tier": 1,
        "manual_note": None,
    },

    # =========================================================================
    # TIER 2 — South Asian Regional (~20 entries)
    # =========================================================================
    {
        "id": "india_updated_ndc_2022",
        "title": "India Updated Nationally Determined Contribution 2022",
        "url": "https://unfccc.int/sites/default/files/NDC/2022-08/India%20Updated%20First%20Nationally%20Determined%20Contrib.pdf",
        "country": "India",
        "region": "South Asia",
        "city": "",
        "sectors": ["transport", "industry", "energy", "waste", "buildings"],
        "year": 2022,
        "policy_type": "framework",
        "scale": "national",
        "effectiveness_rating": "proven",
        "source_organization": "Ministry of Environment, Forest and Climate Change, Government of India",
        "tier": 2,
        "manual_note": None,
    },
    {
        "id": "india_ncap_national_clean_air_programme_2020",
        "title": "India National Clean Air Programme (NCAP) Progress Report 2020",
        "url": None,
        "country": "India",
        "region": "South Asia",
        "city": "",
        "sectors": ["transport", "industry", "energy"],
        "year": 2020,
        "policy_type": "framework",
        "scale": "national",
        "effectiveness_rating": "promising",
        "source_organization": "Central Pollution Control Board (CPCB), India",
        "tier": 2,
        "manual_note": "Available from CPCB website (cpcb.nic.in).",
    },
    {
        "id": "india_ncap_revised_targets_2022",
        "title": "India NCAP Revised City Targets and Strategy 2022",
        "url": None,
        "country": "India",
        "region": "South Asia",
        "city": "",
        "sectors": ["transport", "industry"],
        "year": 2022,
        "policy_type": "framework",
        "scale": "national",
        "effectiveness_rating": "promising",
        "source_organization": "Ministry of Environment, Forest and Climate Change, Government of India",
        "tier": 2,
        "manual_note": "Available from MoEFCC or CPCB India.",
    },
    {
        "id": "india_energy_conservation_building_code_2023",
        "title": "India Energy Conservation Building Code (ECBC) Update 2023",
        "url": None,
        "country": "India",
        "region": "South Asia",
        "city": "",
        "sectors": ["buildings", "energy"],
        "year": 2023,
        "policy_type": "legislation",
        "scale": "national",
        "effectiveness_rating": "proven",
        "source_organization": "Bureau of Energy Efficiency, Government of India",
        "tier": 2,
        "manual_note": "Available from BEE website (beeindia.gov.in).",
    },
    {
        "id": "india_national_green_hydrogen_mission_2023",
        "title": "India National Green Hydrogen Mission 2023",
        "url": None,
        "country": "India",
        "region": "South Asia",
        "city": "",
        "sectors": ["energy", "industry", "transport"],
        "year": 2023,
        "policy_type": "framework",
        "scale": "national",
        "effectiveness_rating": "promising",
        "source_organization": "Ministry of New and Renewable Energy, Government of India",
        "tier": 2,
        "manual_note": "Available from MNRE website (mnre.gov.in).",
    },
    {
        "id": "bangladesh_mujib_climate_prosperity_plan_2021",
        "title": "Bangladesh Mujib Climate Prosperity Plan 2021",
        "url": None,
        "country": "Bangladesh",
        "region": "South Asia",
        "city": "",
        "sectors": ["transport", "industry", "energy", "waste", "buildings"],
        "year": 2021,
        "policy_type": "framework",
        "scale": "national",
        "effectiveness_rating": "promising",
        "source_organization": "Government of Bangladesh",
        "tier": 2,
        "manual_note": "Available from Bangladesh Ministry of Environment or CVF (Climate Vulnerable Forum).",
    },
    {
        "id": "bangladesh_updated_ndc_2021",
        "title": "Bangladesh Updated Nationally Determined Contributions 2021",
        "url": "https://unfccc.int/sites/default/files/NDC/2022-06/NDC_submission_20210826revised.pdf",
        "country": "Bangladesh",
        "region": "South Asia",
        "city": "",
        "sectors": ["transport", "industry", "energy", "waste", "buildings"],
        "year": 2021,
        "policy_type": "framework",
        "scale": "national",
        "effectiveness_rating": "promising",
        "source_organization": "Ministry of Environment, Forest and Climate Change, Bangladesh",
        "tier": 2,
        "manual_note": None,
    },
    {
        "id": "sri_lanka_updated_ndc_2021",
        "title": "Sri Lanka Updated Nationally Determined Contributions 2021",
        "url": "https://unfccc.int/sites/default/files/NDC/2022-09/Sri%20Lanka_NDC_2021.pdf",
        "country": "Sri Lanka",
        "region": "South Asia",
        "city": "",
        "sectors": ["transport", "industry", "energy", "waste"],
        "year": 2021,
        "policy_type": "framework",
        "scale": "national",
        "effectiveness_rating": "promising",
        "source_organization": "Ministry of Environment, Sri Lanka",
        "tier": 2,
        "manual_note": None,
    },
    {
        "id": "nepal_updated_ndc_2020",
        "title": "Nepal Second Nationally Determined Contribution 2020",
        "url": "https://unfccc.int/sites/default/files/NDC/2022-06/Second%20Nationally%20Determined%20Contribution%20%28NDC%29%20-%202020.pdf",
        "country": "Nepal",
        "region": "South Asia",
        "city": "",
        "sectors": ["transport", "industry", "energy", "waste", "buildings"],
        "year": 2020,
        "policy_type": "framework",
        "scale": "national",
        "effectiveness_rating": "promising",
        "source_organization": "Government of Nepal",
        "tier": 2,
        "manual_note": None,
    },
    {
        "id": "nepal_climate_change_policy_2020",
        "title": "Nepal National Climate Change Policy 2020",
        "url": None,
        "country": "Nepal",
        "region": "South Asia",
        "city": "",
        "sectors": ["transport", "industry", "energy", "waste", "buildings"],
        "year": 2020,
        "policy_type": "legislation",
        "scale": "national",
        "effectiveness_rating": "promising",
        "source_organization": "Ministry of Forests and Environment, Nepal",
        "tier": 2,
        "manual_note": "Available from Nepal Ministry of Forests and Environment.",
    },
    {
        "id": "adb_climate_change_south_asia_2022",
        "title": "ADB Climate Change Assessment for South Asia 2022",
        "url": None,
        "country": "Global",
        "region": "South Asia",
        "city": "",
        "sectors": ["transport", "industry", "energy", "waste", "buildings"],
        "year": 2022,
        "policy_type": "technical_report",
        "scale": "regional",
        "effectiveness_rating": "",
        "source_organization": "Asian Development Bank (ADB)",
        "tier": 2,
        "manual_note": "Search ADB publications library (www.adb.org/publications).",
    },
    {
        "id": "adb_pakistan_country_climate_profile_2022",
        "title": "ADB Pakistan Country Climate and Development Report 2022",
        "url": None,
        "country": "Pakistan",
        "region": "South Asia",
        "city": "",
        "sectors": ["transport", "industry", "energy", "waste", "buildings"],
        "year": 2022,
        "policy_type": "technical_report",
        "scale": "national",
        "effectiveness_rating": "",
        "source_organization": "Asian Development Bank (ADB)",
        "tier": 2,
        "manual_note": "Available from ADB publications (www.adb.org/countries/pakistan).",
    },
    {
        "id": "adb_south_asia_clean_energy_transition_2023",
        "title": "ADB South Asia Clean Energy Transition Roadmap 2023",
        "url": None,
        "country": "Global",
        "region": "South Asia",
        "city": "",
        "sectors": ["energy", "industry"],
        "year": 2023,
        "policy_type": "framework",
        "scale": "regional",
        "effectiveness_rating": "promising",
        "source_organization": "Asian Development Bank (ADB)",
        "tier": 2,
        "manual_note": "Available from ADB publications library.",
    },
    {
        "id": "adb_urban_air_quality_south_asia_2021",
        "title": "ADB Urban Air Quality Management in South Asia 2021",
        "url": None,
        "country": "Global",
        "region": "South Asia",
        "city": "",
        "sectors": ["transport", "industry"],
        "year": 2021,
        "policy_type": "technical_report",
        "scale": "regional",
        "effectiveness_rating": "",
        "source_organization": "Asian Development Bank (ADB)",
        "tier": 2,
        "manual_note": "Available from ADB publications library.",
    },
    {
        "id": "world_bank_south_asia_climate_roadmap_2021",
        "title": "World Bank South Asia Climate Roadmap 2021-2025",
        "url": None,
        "country": "Global",
        "region": "South Asia",
        "city": "",
        "sectors": ["transport", "industry", "energy", "waste", "buildings"],
        "year": 2021,
        "policy_type": "framework",
        "scale": "regional",
        "effectiveness_rating": "",
        "source_organization": "World Bank Group",
        "tier": 2,
        "manual_note": "Available from World Bank Open Knowledge Repository.",
    },
    {
        "id": "india_perform_achieve_trade_pat_cycle_vi_2022",
        "title": "India PAT (Perform, Achieve and Trade) Scheme Cycle VI 2022",
        "url": None,
        "country": "India",
        "region": "South Asia",
        "city": "",
        "sectors": ["industry", "energy"],
        "year": 2022,
        "policy_type": "legislation",
        "scale": "national",
        "effectiveness_rating": "proven",
        "source_organization": "Bureau of Energy Efficiency, Government of India",
        "tier": 2,
        "manual_note": "Available from BEE India (beeindia.gov.in).",
    },
    {
        "id": "saarc_environment_action_plan_2022",
        "title": "SAARC Action Plan on Environment and Climate Change 2022-2030",
        "url": None,
        "country": "Global",
        "region": "South Asia",
        "city": "",
        "sectors": ["transport", "industry", "energy", "waste", "buildings"],
        "year": 2022,
        "policy_type": "framework",
        "scale": "regional",
        "effectiveness_rating": "theoretical",
        "source_organization": "South Asian Association for Regional Cooperation (SAARC)",
        "tier": 2,
        "manual_note": "Available from SAARC Secretariat.",
    },
    {
        "id": "india_ev_policy_fame_ii_extension_2022",
        "title": "India FAME-II Electric Vehicle Policy Extension 2022",
        "url": None,
        "country": "India",
        "region": "South Asia",
        "city": "",
        "sectors": ["transport"],
        "year": 2022,
        "policy_type": "legislation",
        "scale": "national",
        "effectiveness_rating": "proven",
        "source_organization": "Ministry of Heavy Industries, Government of India",
        "tier": 2,
        "manual_note": "Available from Ministry of Heavy Industries (fame2.heavyindustries.gov.in).",
    },

    # =========================================================================
    # TIER 3 — International Frameworks (~35 entries)
    # =========================================================================

    # --- IPCC AR6 ---
    {
        "id": "ipcc_ar6_wg3_ch10_transport_2022",
        "title": "IPCC AR6 WG3 Chapter 10: Transport",
        "url": "https://www.ipcc.ch/report/ar6/wg3/downloads/report/IPCC_AR6_WGIII_Chapter10.pdf",
        "country": "Global",
        "region": "",
        "city": "",
        "sectors": ["transport"],
        "year": 2022,
        "policy_type": "technical_report",
        "scale": "international",
        "effectiveness_rating": "proven",
        "source_organization": "Intergovernmental Panel on Climate Change (IPCC)",
        "tier": 3,
        "manual_note": None,
    },
    {
        "id": "ipcc_ar6_wg3_ch11_industry_2022",
        "title": "IPCC AR6 WG3 Chapter 11: Industry",
        "url": "https://www.ipcc.ch/report/ar6/wg3/downloads/report/IPCC_AR6_WGIII_Chapter11.pdf",
        "country": "Global",
        "region": "",
        "city": "",
        "sectors": ["industry"],
        "year": 2022,
        "policy_type": "technical_report",
        "scale": "international",
        "effectiveness_rating": "proven",
        "source_organization": "Intergovernmental Panel on Climate Change (IPCC)",
        "tier": 3,
        "manual_note": None,
    },
    {
        "id": "ipcc_ar6_wg3_ch6_energy_systems_2022",
        "title": "IPCC AR6 WG3 Chapter 6: Energy Systems",
        "url": "https://www.ipcc.ch/report/ar6/wg3/downloads/report/IPCC_AR6_WGIII_Chapter06.pdf",
        "country": "Global",
        "region": "",
        "city": "",
        "sectors": ["energy"],
        "year": 2022,
        "policy_type": "technical_report",
        "scale": "international",
        "effectiveness_rating": "proven",
        "source_organization": "Intergovernmental Panel on Climate Change (IPCC)",
        "tier": 3,
        "manual_note": None,
    },
    {
        "id": "ipcc_ar6_wg3_ch9_buildings_2022",
        "title": "IPCC AR6 WG3 Chapter 9: Buildings",
        "url": "https://www.ipcc.ch/report/ar6/wg3/downloads/report/IPCC_AR6_WGIII_Chapter09.pdf",
        "country": "Global",
        "region": "",
        "city": "",
        "sectors": ["buildings"],
        "year": 2022,
        "policy_type": "technical_report",
        "scale": "international",
        "effectiveness_rating": "proven",
        "source_organization": "Intergovernmental Panel on Climate Change (IPCC)",
        "tier": 3,
        "manual_note": None,
    },
    {
        "id": "ipcc_ar6_wg3_ch8_urban_2022",
        "title": "IPCC AR6 WG3 Chapter 8: Urban Systems and Other Settlements",
        "url": "https://www.ipcc.ch/report/ar6/wg3/downloads/report/IPCC_AR6_WGIII_Chapter08.pdf",
        "country": "Global",
        "region": "",
        "city": "",
        "sectors": ["transport", "buildings", "waste", "energy"],
        "year": 2022,
        "policy_type": "technical_report",
        "scale": "international",
        "effectiveness_rating": "proven",
        "source_organization": "Intergovernmental Panel on Climate Change (IPCC)",
        "tier": 3,
        "manual_note": None,
    },
    {
        "id": "ipcc_ar6_synthesis_report_2023",
        "title": "IPCC AR6 Synthesis Report: Climate Change 2023",
        "url": "https://www.ipcc.ch/report/ar6/syr/downloads/report/IPCC_AR6_SYR_LongerReport.pdf",
        "country": "Global",
        "region": "",
        "city": "",
        "sectors": ["transport", "industry", "energy", "waste", "buildings"],
        "year": 2023,
        "policy_type": "technical_report",
        "scale": "international",
        "effectiveness_rating": "proven",
        "source_organization": "Intergovernmental Panel on Climate Change (IPCC)",
        "tier": 3,
        "manual_note": None,
    },

    # --- UNFCCC / COP ---
    {
        "id": "glasgow_climate_pact_2021",
        "title": "Glasgow Climate Pact (COP26 Outcome) 2021",
        "url": "https://unfccc.int/sites/default/files/resource/cop26_auv_2f_cover_decision.pdf",
        "country": "Global",
        "region": "",
        "city": "",
        "sectors": ["transport", "industry", "energy", "waste", "buildings"],
        "year": 2021,
        "policy_type": "framework",
        "scale": "international",
        "effectiveness_rating": "proven",
        "source_organization": "UNFCCC",
        "tier": 3,
        "manual_note": None,
    },
    {
        "id": "cop27_sharm_el_sheikh_implementation_plan_2022",
        "title": "Sharm el-Sheikh Implementation Plan (COP27 Outcome) 2022",
        "url": "https://unfccc.int/sites/default/files/resource/cop27_auv_2_cover%20decision.pdf",
        "country": "Global",
        "region": "",
        "city": "",
        "sectors": ["transport", "industry", "energy", "waste", "buildings"],
        "year": 2022,
        "policy_type": "framework",
        "scale": "international",
        "effectiveness_rating": "proven",
        "source_organization": "UNFCCC",
        "tier": 3,
        "manual_note": None,
    },
    {
        "id": "cop28_uae_consensus_global_stocktake_2023",
        "title": "UAE Consensus — COP28 Global Stocktake Outcome 2023",
        "url": "https://unfccc.int/sites/default/files/resource/cop28_auv_1_gst.pdf",
        "country": "Global",
        "region": "",
        "city": "",
        "sectors": ["transport", "industry", "energy", "waste", "buildings"],
        "year": 2023,
        "policy_type": "framework",
        "scale": "international",
        "effectiveness_rating": "proven",
        "source_organization": "UNFCCC",
        "tier": 3,
        "manual_note": None,
    },

    # --- EU ---
    {
        "id": "eu_green_deal_2020",
        "title": "European Green Deal Communication 2020",
        "url": None,
        "country": "EU",
        "region": "",
        "city": "",
        "sectors": ["transport", "industry", "energy", "waste", "buildings"],
        "year": 2020,
        "policy_type": "framework",
        "scale": "international",
        "effectiveness_rating": "proven",
        "source_organization": "European Commission",
        "tier": 3,
        "manual_note": "Available from EUR-Lex (eur-lex.europa.eu).",
    },
    {
        "id": "eu_cbam_regulation_2023",
        "title": "EU Carbon Border Adjustment Mechanism (CBAM) Regulation 2023",
        "url": None,
        "country": "EU",
        "region": "",
        "city": "",
        "sectors": ["industry", "energy"],
        "year": 2023,
        "policy_type": "legislation",
        "scale": "international",
        "effectiveness_rating": "proven",
        "source_organization": "European Parliament / Council of the European Union",
        "tier": 3,
        "manual_note": "Available from EUR-Lex. Regulation (EU) 2023/956.",
    },
    {
        "id": "eu_fit_for_55_package_2021",
        "title": "EU Fit for 55 Package 2021",
        "url": None,
        "country": "EU",
        "region": "",
        "city": "",
        "sectors": ["transport", "industry", "energy", "buildings"],
        "year": 2021,
        "policy_type": "legislation",
        "scale": "international",
        "effectiveness_rating": "proven",
        "source_organization": "European Commission",
        "tier": 3,
        "manual_note": "Available from European Commission climate policy pages.",
    },

    # --- IEA ---
    {
        "id": "iea_net_zero_roadmap_2021",
        "title": "IEA Net Zero by 2050: A Roadmap for the Global Energy Sector (2021)",
        "url": "https://iea.blob.core.windows.net/assets/deebef5d-0c34-4539-9d0c-10b13d840027/NetZeroby2050-ARoadmapfortheGlobalEnergySector_CORR.pdf",
        "country": "Global",
        "region": "",
        "city": "",
        "sectors": ["transport", "industry", "energy", "buildings"],
        "year": 2021,
        "policy_type": "framework",
        "scale": "international",
        "effectiveness_rating": "proven",
        "source_organization": "International Energy Agency (IEA)",
        "tier": 3,
        "manual_note": None,
    },
    {
        "id": "iea_net_zero_roadmap_update_2023",
        "title": "IEA Net Zero Roadmap: A Global Pathway to Keep 1.5C Goal in Reach (2023 Update)",
        "url": "https://iea.blob.core.windows.net/assets/13dab083-08c3-4dfd-a887-42a3ebe533bc/NetZeroRoadmap_AGlobalPathwaytoKeepthe1.5CGoalinReach-2023Update.pdf",
        "country": "Global",
        "region": "",
        "city": "",
        "sectors": ["transport", "industry", "energy", "buildings"],
        "year": 2023,
        "policy_type": "framework",
        "scale": "international",
        "effectiveness_rating": "proven",
        "source_organization": "International Energy Agency (IEA)",
        "tier": 3,
        "manual_note": None,
    },
    {
        "id": "iea_world_energy_outlook_2023",
        "title": "IEA World Energy Outlook 2023",
        "url": None,
        "country": "Global",
        "region": "",
        "city": "",
        "sectors": ["energy", "industry", "transport", "buildings"],
        "year": 2023,
        "policy_type": "technical_report",
        "scale": "international",
        "effectiveness_rating": "proven",
        "source_organization": "International Energy Agency (IEA)",
        "tier": 3,
        "manual_note": "Available for purchase/free summary from IEA (www.iea.org/reports/world-energy-outlook-2023).",
    },
    {
        "id": "iea_energy_efficiency_2023",
        "title": "IEA Energy Efficiency 2023",
        "url": None,
        "country": "Global",
        "region": "",
        "city": "",
        "sectors": ["energy", "buildings", "industry"],
        "year": 2023,
        "policy_type": "technical_report",
        "scale": "international",
        "effectiveness_rating": "proven",
        "source_organization": "International Energy Agency (IEA)",
        "tier": 3,
        "manual_note": "Available from IEA website (www.iea.org/reports/energy-efficiency-2023).",
    },

    # --- IRENA ---
    {
        "id": "irena_world_energy_transitions_outlook_2023",
        "title": "IRENA World Energy Transitions Outlook 2023",
        "url": "https://www.irena.org/-/media/Files/IRENA/Agency/Publication/2023/Jun/IRENA_World_Energy_Transitions_Outlook_2023.pdf",
        "country": "Global",
        "region": "",
        "city": "",
        "sectors": ["energy", "transport", "industry", "buildings"],
        "year": 2023,
        "policy_type": "framework",
        "scale": "international",
        "effectiveness_rating": "proven",
        "source_organization": "International Renewable Energy Agency (IRENA)",
        "tier": 3,
        "manual_note": None,
    },
    {
        "id": "irena_renewable_energy_statistics_2023",
        "title": "IRENA Renewable Energy Statistics 2023",
        "url": "https://www.irena.org/-/media/Files/IRENA/Agency/Publication/2023/Jul/IRENA_Renewable_energy_statistics_2023.pdf",
        "country": "Global",
        "region": "",
        "city": "",
        "sectors": ["energy"],
        "year": 2023,
        "policy_type": "technical_report",
        "scale": "international",
        "effectiveness_rating": "",
        "source_organization": "International Renewable Energy Agency (IRENA)",
        "tier": 3,
        "manual_note": None,
    },
    {
        "id": "irena_renewable_power_generation_costs_2022",
        "title": "IRENA Renewable Power Generation Costs in 2022",
        "url": "https://www.irena.org/-/media/Files/IRENA/Agency/Publication/2023/Aug/IRENA_Renewable_power_generation_costs_in_2022.pdf",
        "country": "Global",
        "region": "",
        "city": "",
        "sectors": ["energy"],
        "year": 2023,
        "policy_type": "technical_report",
        "scale": "international",
        "effectiveness_rating": "proven",
        "source_organization": "International Renewable Energy Agency (IRENA)",
        "tier": 3,
        "manual_note": None,
    },

    # --- UNEP ---
    {
        "id": "unep_emissions_gap_report_2023",
        "title": "UNEP Emissions Gap Report 2023",
        "url": "https://wedocs.unep.org/bitstream/handle/20.500.11822/43922/EGR2023.pdf",
        "country": "Global",
        "region": "",
        "city": "",
        "sectors": ["transport", "industry", "energy", "waste", "buildings"],
        "year": 2023,
        "policy_type": "technical_report",
        "scale": "international",
        "effectiveness_rating": "proven",
        "source_organization": "United Nations Environment Programme (UNEP)",
        "tier": 3,
        "manual_note": None,
    },
    {
        "id": "unep_emissions_gap_report_2022",
        "title": "UNEP Emissions Gap Report 2022: The Closing Window",
        "url": "https://wedocs.unep.org/bitstream/handle/20.500.11822/40874/EGR2022.pdf",
        "country": "Global",
        "region": "",
        "city": "",
        "sectors": ["transport", "industry", "energy", "waste", "buildings"],
        "year": 2022,
        "policy_type": "technical_report",
        "scale": "international",
        "effectiveness_rating": "proven",
        "source_organization": "United Nations Environment Programme (UNEP)",
        "tier": 3,
        "manual_note": None,
    },
    {
        "id": "unep_global_waste_management_outlook_2024",
        "title": "UNEP Global Waste Management Outlook 2024",
        "url": None,
        "country": "Global",
        "region": "",
        "city": "",
        "sectors": ["waste"],
        "year": 2024,
        "policy_type": "technical_report",
        "scale": "international",
        "effectiveness_rating": "proven",
        "source_organization": "United Nations Environment Programme (UNEP)",
        "tier": 3,
        "manual_note": "Available from UNEP publications (www.unep.org/resources).",
    },

    # --- World Bank / Carbon Pricing ---
    {
        "id": "world_bank_state_carbon_pricing_2023",
        "title": "World Bank State and Trends of Carbon Pricing 2023",
        "url": "https://openknowledge.worldbank.org/bitstreams/6e2e3e84-2789-5264-8b64-7e5eb1e8bfac/download",
        "country": "Global",
        "region": "",
        "city": "",
        "sectors": ["industry", "energy", "transport"],
        "year": 2023,
        "policy_type": "technical_report",
        "scale": "international",
        "effectiveness_rating": "proven",
        "source_organization": "World Bank Group",
        "tier": 3,
        "manual_note": None,
    },
    {
        "id": "world_bank_state_carbon_pricing_2022",
        "title": "World Bank State and Trends of Carbon Pricing 2022",
        "url": None,
        "country": "Global",
        "region": "",
        "city": "",
        "sectors": ["industry", "energy", "transport"],
        "year": 2022,
        "policy_type": "technical_report",
        "scale": "international",
        "effectiveness_rating": "proven",
        "source_organization": "World Bank Group",
        "tier": 3,
        "manual_note": "Available from World Bank Open Knowledge Repository.",
    },
    {
        "id": "world_bank_ccdr_pakistan_2022",
        "title": "World Bank Country Climate and Development Report: Pakistan 2022",
        "url": None,
        "country": "Pakistan",
        "region": "",
        "city": "",
        "sectors": ["transport", "industry", "energy", "waste", "buildings"],
        "year": 2022,
        "policy_type": "technical_report",
        "scale": "national",
        "effectiveness_rating": "",
        "source_organization": "World Bank Group",
        "tier": 3,
        "manual_note": "Available from World Bank Open Knowledge Repository.",
    },

    # --- WHO ---
    {
        "id": "who_air_quality_guidelines_2021",
        "title": "WHO Global Air Quality Guidelines 2021",
        "url": "https://iris.who.int/bitstream/handle/10665/345329/9789240034228-eng.pdf",
        "country": "Global",
        "region": "",
        "city": "",
        "sectors": ["transport", "industry", "energy"],
        "year": 2021,
        "policy_type": "guideline",
        "scale": "international",
        "effectiveness_rating": "proven",
        "source_organization": "World Health Organization (WHO)",
        "tier": 3,
        "manual_note": None,
    },

    # --- Global Methane ---
    {
        "id": "global_methane_pledge_2021",
        "title": "Global Methane Pledge 2021",
        "url": None,
        "country": "Global",
        "region": "",
        "city": "",
        "sectors": ["waste", "energy", "industry"],
        "year": 2021,
        "policy_type": "framework",
        "scale": "international",
        "effectiveness_rating": "promising",
        "source_organization": "US Government / EU / UNEP",
        "tier": 3,
        "manual_note": "Details at www.globalmethanepledge.org.",
    },
    {
        "id": "unep_global_methane_assessment_2021",
        "title": "UNEP Global Methane Assessment 2021",
        "url": "https://wedocs.unep.org/bitstream/handle/20.500.11822/35917/GMA.pdf",
        "country": "Global",
        "region": "",
        "city": "",
        "sectors": ["waste", "energy", "industry"],
        "year": 2021,
        "policy_type": "technical_report",
        "scale": "international",
        "effectiveness_rating": "proven",
        "source_organization": "United Nations Environment Programme (UNEP) / Climate and Clean Air Coalition",
        "tier": 3,
        "manual_note": None,
    },

    # --- Paris Agreement / Long-term strategies ---
    {
        "id": "unfccc_paris_agreement_global_stocktake_technical_synthesis_2023",
        "title": "UNFCCC Technical Synthesis for the First Global Stocktake 2023",
        "url": None,
        "country": "Global",
        "region": "",
        "city": "",
        "sectors": ["transport", "industry", "energy", "waste", "buildings"],
        "year": 2023,
        "policy_type": "technical_report",
        "scale": "international",
        "effectiveness_rating": "",
        "source_organization": "UNFCCC",
        "tier": 3,
        "manual_note": "Available from UNFCCC Global Stocktake portal.",
    },

    # --- Other international ---
    {
        "id": "un_habitat_world_cities_report_2022",
        "title": "UN-Habitat World Cities Report 2022: Envisaging the Future of Cities",
        "url": None,
        "country": "Global",
        "region": "",
        "city": "",
        "sectors": ["transport", "buildings", "waste", "energy"],
        "year": 2022,
        "policy_type": "technical_report",
        "scale": "international",
        "effectiveness_rating": "",
        "source_organization": "United Nations Human Settlements Programme (UN-Habitat)",
        "tier": 3,
        "manual_note": "Available from UN-Habitat (unhabitat.org).",
    },
    {
        "id": "global_alliance_buildings_construction_2022",
        "title": "GlobalABC 2022 Global Status Report for Buildings and Construction",
        "url": None,
        "country": "Global",
        "region": "",
        "city": "",
        "sectors": ["buildings"],
        "year": 2022,
        "policy_type": "technical_report",
        "scale": "international",
        "effectiveness_rating": "proven",
        "source_organization": "Global Alliance for Buildings and Construction / UNEP",
        "tier": 3,
        "manual_note": "Available from globalabc.org.",
    },
    {
        "id": "undp_climate_promise_progress_report_2023",
        "title": "UNDP Climate Promise Progress Report 2023",
        "url": None,
        "country": "Global",
        "region": "",
        "city": "",
        "sectors": ["transport", "industry", "energy", "waste", "buildings"],
        "year": 2023,
        "policy_type": "technical_report",
        "scale": "international",
        "effectiveness_rating": "",
        "source_organization": "United Nations Development Programme (UNDP)",
        "tier": 3,
        "manual_note": "Available from UNDP Climate Promise (climatepromise.undp.org).",
    },
    {
        "id": "iea_co2_emissions_energy_combustion_2023",
        "title": "IEA CO2 Emissions in 2023",
        "url": None,
        "country": "Global",
        "region": "",
        "city": "",
        "sectors": ["energy", "industry", "transport"],
        "year": 2024,
        "policy_type": "technical_report",
        "scale": "international",
        "effectiveness_rating": "",
        "source_organization": "International Energy Agency (IEA)",
        "tier": 3,
        "manual_note": "Available from IEA website (www.iea.org).",
    },
    {
        "id": "climate_action_tracker_global_update_2023",
        "title": "Climate Action Tracker Global Update December 2023",
        "url": None,
        "country": "Global",
        "region": "",
        "city": "",
        "sectors": ["transport", "industry", "energy", "waste", "buildings"],
        "year": 2023,
        "policy_type": "technical_report",
        "scale": "international",
        "effectiveness_rating": "",
        "source_organization": "Climate Analytics / NewClimate Institute",
        "tier": 3,
        "manual_note": "Available from climateactiontracker.org.",
    },

    # =========================================================================
    # TIER 4 — Case Studies (~18 entries)
    # =========================================================================
    {
        "id": "singapore_green_plan_2030",
        "title": "Singapore Green Plan 2030",
        "url": None,
        "country": "Singapore",
        "region": "",
        "city": "Singapore",
        "sectors": ["transport", "industry", "energy", "waste", "buildings"],
        "year": 2021,
        "policy_type": "framework",
        "scale": "national",
        "effectiveness_rating": "proven",
        "source_organization": "Government of Singapore",
        "tier": 4,
        "manual_note": "Available from www.greenplan.gov.sg.",
    },
    {
        "id": "uae_net_zero_2050_strategy",
        "title": "UAE Net Zero by 2050 Strategic Initiative",
        "url": None,
        "country": "UAE",
        "region": "",
        "city": "",
        "sectors": ["transport", "industry", "energy", "waste", "buildings"],
        "year": 2021,
        "policy_type": "framework",
        "scale": "national",
        "effectiveness_rating": "promising",
        "source_organization": "Government of the United Arab Emirates",
        "tier": 4,
        "manual_note": "Available from UAE climate action portal.",
    },
    {
        "id": "delhi_ncr_grap_2022",
        "title": "Delhi NCR Graded Response Action Plan (GRAP) 2022 Revision",
        "url": None,
        "country": "India",
        "region": "South Asia",
        "city": "Delhi",
        "sectors": ["transport", "industry"],
        "year": 2022,
        "policy_type": "legislation",
        "scale": "local",
        "effectiveness_rating": "proven",
        "source_organization": "Commission for Air Quality Management, Government of India",
        "tier": 4,
        "manual_note": "Available from CAQM (caqm.nic.in) or CPCB India.",
    },
    {
        "id": "delhi_ev_policy_2020",
        "title": "Delhi Electric Vehicle Policy 2020",
        "url": None,
        "country": "India",
        "region": "South Asia",
        "city": "Delhi",
        "sectors": ["transport"],
        "year": 2020,
        "policy_type": "legislation",
        "scale": "local",
        "effectiveness_rating": "proven",
        "source_organization": "Government of NCT of Delhi",
        "tier": 4,
        "manual_note": "Available from Delhi Transport Department.",
    },
    {
        "id": "jakarta_air_quality_action_plan_2023",
        "title": "Jakarta Air Quality Improvement Action Plan 2023",
        "url": None,
        "country": "Indonesia",
        "region": "",
        "city": "Jakarta",
        "sectors": ["transport", "industry"],
        "year": 2023,
        "policy_type": "framework",
        "scale": "local",
        "effectiveness_rating": "promising",
        "source_organization": "Jakarta Provincial Government",
        "tier": 4,
        "manual_note": "Available from Jakarta Provincial Government environment agency.",
    },
    {
        "id": "saudi_green_initiative_2021",
        "title": "Saudi Green Initiative 2021",
        "url": None,
        "country": "Saudi Arabia",
        "region": "",
        "city": "",
        "sectors": ["energy", "industry", "transport"],
        "year": 2021,
        "policy_type": "framework",
        "scale": "national",
        "effectiveness_rating": "promising",
        "source_organization": "Government of Saudi Arabia",
        "tier": 4,
        "manual_note": "Available from www.saudigreeninitiative.org.",
    },
    {
        "id": "c40_cities_air_quality_network_report_2022",
        "title": "C40 Cities Air Quality Good Practice Guide 2022",
        "url": None,
        "country": "Global",
        "region": "",
        "city": "",
        "sectors": ["transport", "industry", "energy"],
        "year": 2022,
        "policy_type": "guideline",
        "scale": "international",
        "effectiveness_rating": "proven",
        "source_organization": "C40 Cities Climate Leadership Group",
        "tier": 4,
        "manual_note": "Available from C40 Knowledge Hub (www.c40knowledgehub.org).",
    },
    {
        "id": "c40_cities_clean_construction_guide_2023",
        "title": "C40 Cities Clean Construction Policy Guide 2023",
        "url": None,
        "country": "Global",
        "region": "",
        "city": "",
        "sectors": ["buildings", "industry"],
        "year": 2023,
        "policy_type": "guideline",
        "scale": "international",
        "effectiveness_rating": "promising",
        "source_organization": "C40 Cities Climate Leadership Group",
        "tier": 4,
        "manual_note": "Available from C40 Knowledge Hub.",
    },
    {
        "id": "c40_zero_waste_declaration_progress_2022",
        "title": "C40 Advancing Towards Zero Waste Declaration Progress Report 2022",
        "url": None,
        "country": "Global",
        "region": "",
        "city": "",
        "sectors": ["waste"],
        "year": 2022,
        "policy_type": "case_study",
        "scale": "international",
        "effectiveness_rating": "proven",
        "source_organization": "C40 Cities Climate Leadership Group",
        "tier": 4,
        "manual_note": "Available from C40 Knowledge Hub.",
    },
    {
        "id": "bogota_ciclovia_sustainable_transport_case_study_2021",
        "title": "Bogota Ciclovia and Sustainable Transport: Case Study 2021",
        "url": None,
        "country": "Colombia",
        "region": "",
        "city": "Bogota",
        "sectors": ["transport"],
        "year": 2021,
        "policy_type": "case_study",
        "scale": "local",
        "effectiveness_rating": "proven",
        "source_organization": "ITDP / C40 Cities",
        "tier": 4,
        "manual_note": "Available from ITDP (www.itdp.org) publications.",
    },
    {
        "id": "medellín_metrocable_transport_equity_case_study_2022",
        "title": "Medellin Metrocable Urban Transport and Equity Case Study 2022",
        "url": None,
        "country": "Colombia",
        "region": "",
        "city": "Medellin",
        "sectors": ["transport"],
        "year": 2022,
        "policy_type": "case_study",
        "scale": "local",
        "effectiveness_rating": "proven",
        "source_organization": "World Resources Institute (WRI)",
        "tier": 4,
        "manual_note": "Available from WRI publications (www.wri.org).",
    },
    {
        "id": "bangkok_clean_air_plan_2022",
        "title": "Bangkok Metropolitan Clean Air Action Plan 2022",
        "url": None,
        "country": "Thailand",
        "region": "",
        "city": "Bangkok",
        "sectors": ["transport", "industry"],
        "year": 2022,
        "policy_type": "framework",
        "scale": "local",
        "effectiveness_rating": "promising",
        "source_organization": "Bangkok Metropolitan Administration",
        "tier": 4,
        "manual_note": "Available from Bangkok Metropolitan Administration or Pollution Control Department.",
    },
    {
        "id": "cairo_sustainable_transport_strategy_2023",
        "title": "Cairo Sustainable Urban Transport Strategy 2023",
        "url": None,
        "country": "Egypt",
        "region": "",
        "city": "Cairo",
        "sectors": ["transport"],
        "year": 2023,
        "policy_type": "framework",
        "scale": "local",
        "effectiveness_rating": "promising",
        "source_organization": "Greater Cairo Transport Regulatory Authority",
        "tier": 4,
        "manual_note": "Available from Egypt Ministry of Transport or GIZ Egypt.",
    },
    {
        "id": "nairobi_integrated_waste_management_2021",
        "title": "Nairobi Integrated Solid Waste Management Plan 2021",
        "url": None,
        "country": "Kenya",
        "region": "",
        "city": "Nairobi",
        "sectors": ["waste"],
        "year": 2021,
        "policy_type": "case_study",
        "scale": "local",
        "effectiveness_rating": "promising",
        "source_organization": "Nairobi City County Government / JICA",
        "tier": 4,
        "manual_note": "Available from Nairobi County or JICA publications.",
    },
    {
        "id": "addis_ababa_lrt_emissions_case_study_2022",
        "title": "Addis Ababa Light Rail Transit Emissions Reduction Case Study 2022",
        "url": None,
        "country": "Ethiopia",
        "region": "",
        "city": "Addis Ababa",
        "sectors": ["transport"],
        "year": 2022,
        "policy_type": "case_study",
        "scale": "local",
        "effectiveness_rating": "proven",
        "source_organization": "UNEP / Ethiopian Railways Corporation",
        "tier": 4,
        "manual_note": "Available from UNEP publications.",
    },
    {
        "id": "kuala_lumpur_low_carbon_city_framework_2021",
        "title": "Kuala Lumpur Low Carbon City Framework 2021",
        "url": None,
        "country": "Malaysia",
        "region": "",
        "city": "Kuala Lumpur",
        "sectors": ["transport", "buildings", "energy", "waste"],
        "year": 2021,
        "policy_type": "framework",
        "scale": "local",
        "effectiveness_rating": "promising",
        "source_organization": "Kuala Lumpur City Hall / Ministry of Environment and Water, Malaysia",
        "tier": 4,
        "manual_note": "Available from Malaysia Green Technology and Climate Change Corporation.",
    },
    {
        "id": "hanoi_clean_air_plan_2021",
        "title": "Hanoi Clean Air Action Plan 2021-2025",
        "url": None,
        "country": "Vietnam",
        "region": "",
        "city": "Hanoi",
        "sectors": ["transport", "industry"],
        "year": 2021,
        "policy_type": "framework",
        "scale": "local",
        "effectiveness_rating": "promising",
        "source_organization": "Hanoi People's Committee",
        "tier": 4,
        "manual_note": "Available from Hanoi DONRE or Clean Air Asia.",
    },
    {
        "id": "mumbai_climate_action_plan_2022",
        "title": "Mumbai Climate Action Plan 2022",
        "url": None,
        "country": "India",
        "region": "South Asia",
        "city": "Mumbai",
        "sectors": ["transport", "industry", "energy", "waste", "buildings"],
        "year": 2022,
        "policy_type": "framework",
        "scale": "local",
        "effectiveness_rating": "promising",
        "source_organization": "Municipal Corporation of Greater Mumbai / WRI India",
        "tier": 4,
        "manual_note": "Available from MCGM or WRI India.",
    },
]
