# Generated by Django 5.2.9 on 2026-03-26 11:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('source_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('sectors', models.JSONField(default=list)),
                ('year', models.IntegerField()),
                ('policy_type', models.CharField(choices=[('legislation', 'Legislation'), ('framework', 'Framework'), ('guideline', 'Guideline'), ('case_study', 'Case Study'), ('technical_report', 'Technical Report')], max_length=50)),
                ('scale', models.CharField(choices=[('local', 'Local'), ('national', 'National'), ('regional', 'Regional'), ('international', 'International')], max_length=20)),
                ('effectiveness_rating', models.CharField(blank=True, choices=[('proven', 'Proven'), ('promising', 'Promising'), ('theoretical', 'Theoretical')], default='', max_length=20)),
                ('source_organization', models.CharField(max_length=255)),
                ('chunk_count', models.IntegerField(default=0)),
                ('is_indexed', models.BooleanField(default=False)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'policy_documents',
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('area_id', models.CharField(default='', max_length=255)),
                ('sector', models.CharField(max_length=50)),
                ('response_data', models.JSONField()),
                ('confidence_scores', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('policy_doc_count', models.IntegerField(default=0)),
                ('emissions_data_hash', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'recommendation_cache',
                'indexes': [models.Index(fields=['area_id', 'sector'], name='recommendat_area_id_4b61e4_idx'), models.Index(fields=['expires_at'], name='recommendat_expires_e3f417_idx')],
                'unique_together': {('area_id', 'sector')},
            },
        ),
        migrations.CreateModel(
            name='ScrapedArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('url', models.URLField(max_length=2000, unique=True)),
                ('source', models.CharField(choices=[('carbon_brief', 'Carbon Brief'), ('climate_home', 'Climate Home News'), ('unfccc', 'UNFCCC News'), ('iea', 'IEA News'), ('dawn_climate', 'Dawn (Pakistan) Climate'), ('the_news_pk', 'The News International Pakistan'), ('world_bank', 'World Bank Climate'), ('reuters_climate', 'Reuters Climate'), ('pakistan_govt', 'Pakistan Government'), ('unep', 'UNEP News'), ('irena', 'IRENA News'), ('custom_rss', 'Custom RSS Feed')], max_length=50)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True, default='')),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('country', models.CharField(default='Global', max_length=100)),
                ('sectors', models.JSONField(default=list)),
                ('relevance_score', models.FloatField(default=0.0)),
                ('is_indexed', models.BooleanField(default=False)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'scraped_articles',
                'ordering': ['-published_date'],
                'indexes': [models.Index(fields=['source', '-published_date'], name='scraped_art_source_1a7220_idx'), models.Index(fields=['is_indexed'], name='scraped_art_is_inde_0fdefc_idx'), models.Index(fields=['-relevance_score'], name='scraped_art_relevan_b575dd_idx')],
            },
        ),
    ]
