# Generated by Django 5.2.9 on 2026-03-23 20:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('source_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('sectors', models.JSONField(default=list)),
                ('year', models.IntegerField()),
                ('policy_type', models.CharField(choices=[('legislation', 'Legislation'), ('framework', 'Framework'), ('guideline', 'Guideline'), ('case_study', 'Case Study'), ('technical_report', 'Technical Report')], max_length=50)),
                ('scale', models.CharField(choices=[('local', 'Local'), ('national', 'National'), ('regional', 'Regional'), ('international', 'International')], max_length=20)),
                ('effectiveness_rating', models.CharField(blank=True, choices=[('proven', 'Proven'), ('promising', 'Promising'), ('theoretical', 'Theoretical')], default='', max_length=20)),
                ('source_organization', models.CharField(max_length=255)),
                ('chunk_count', models.IntegerField(default=0)),
                ('is_indexed', models.BooleanField(default=False)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'policy_documents',
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sector', models.CharField(max_length=50)),
                ('response_data', models.JSONField()),
                ('confidence_scores', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('policy_doc_count', models.IntegerField(default=0)),
                ('emissions_data_hash', models.CharField(max_length=64)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_caches', to='api.areainfo')),
            ],
            options={
                'db_table': 'recommendation_cache',
                'indexes': [models.Index(fields=['area', 'sector'], name='recommendat_area_id_4b61e4_idx'), models.Index(fields=['expires_at'], name='recommendat_expires_e3f417_idx')],
                'unique_together': {('area', 'sector')},
            },
        ),
    ]
