# Generated by Django 5.2.9 on 2026-04-25 14:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('area_id', models.CharField(max_length=255)),
                ('area_name', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=50)),
                ('coordinates', models.JSONField(default=dict)),
                ('content_json', models.JSONField()),
                ('retrieved_context', models.JSONField(default=dict)),
                ('model_used', models.CharField(blank=True, default='', max_length=120)),
                ('provider', models.CharField(blank=True, default='', max_length=30)),
                ('generation_ms', models.IntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'recommendations',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['area_id', 'sector'], name='recommendat_area_id_97ad72_idx'), models.Index(fields=['-generated_at'], name='recommendat_generat_387346_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecommendationConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('messages', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='recommendations.recommendation')),
            ],
            options={
                'db_table': 'recommendation_conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(choices=[('summary', 'Summary'), ('immediate_actions', 'Immediate Actions'), ('long_term_strategies', 'Long-term Strategies'), ('policy_recommendations', 'Policy Recommendations'), ('monitoring_metrics', 'Monitoring Metrics'), ('risk_factors', 'Risk Factors'), ('overall', 'Overall')], max_length=40)),
                ('rating', models.SmallIntegerField()),
                ('comment', models.TextField(blank=True, default='')),
                ('used_in_prompt', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='recommendations.recommendation')),
            ],
            options={
                'db_table': 'recommendation_feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['rating', '-created_at'], name='recommendat_rating_8f6253_idx'), models.Index(fields=['recommendation', 'section'], name='recommendat_recomme_dfa323_idx')],
            },
        ),
    ]
