# Generated by Django 5.2.9 on 2026-03-23 21:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('url', models.URLField(max_length=2000, unique=True)),
                ('source', models.CharField(choices=[('carbon_brief', 'Carbon Brief'), ('climate_home', 'Climate Home News'), ('unfccc', 'UNFCCC News'), ('iea', 'IEA News'), ('dawn_climate', 'Dawn (Pakistan) Climate'), ('the_news_pk', 'The News International Pakistan'), ('world_bank', 'World Bank Climate'), ('reuters_climate', 'Reuters Climate'), ('pakistan_govt', 'Pakistan Government'), ('unep', 'UNEP News'), ('irena', 'IRENA News'), ('custom_rss', 'Custom RSS Feed')], max_length=50)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True, default='')),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('country', models.CharField(default='Global', max_length=100)),
                ('sectors', models.JSONField(default=list)),
                ('relevance_score', models.FloatField(default=0.0)),
                ('is_indexed', models.BooleanField(default=False)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'scraped_articles',
                'ordering': ['-published_date'],
                'indexes': [models.Index(fields=['source', '-published_date'], name='scraped_art_source_1a7220_idx'), models.Index(fields=['is_indexed'], name='scraped_art_is_inde_0fdefc_idx'), models.Index(fields=['-relevance_score'], name='scraped_art_relevan_b575dd_idx')],
            },
        ),
    ]
